### ISSUE TITLE
Play Store Data Safety Section

### ISSUE THREAD

**Issue by vaibhavantil1** [akitikkx/upnext#33]
**Is your feature request related to a problem? Please describe.**
Add a section for Play Store Data Safety Section. 

**Describe the solution you'd like**
In the recent Play Store policy, it will become mandatory for you to fill out the Data Safety Section. Since this is an OSS Android app, it will make sense to have it as a part of the repository as well.

**Describe alternatives you've considered**
I have run the scan using [my tool here](https://github.com/Privado-Inc/privado) on your repo, attached are
the scan results. I found the following 4 data types & 2 SDKs.

If this is helpful, do use our free tool to generate Play Store Data Safety report: https://github.com/Privado-Inc/privado
Would love your feedback!
![image](https://user-images.githubusercontent.com/87804852/156793710-fe012e83-0a75-4d72-8d04-320f9556d321.png)
![image](https://user-images.githubusercontent.com/87804852/156793748-3a0759a9-41df-47ee-aebc-61c5260de1cc.png)
![image](https://user-images.githubusercontent.com/87804852/156793773-97447e6f-a297-4378-a536-5884e2503405.png)

**Comment by akitikkx** [comment]
Thank you @vaibhavantil1. The data safety section has been completed on the Play Store and accepted. I have added the CSV export and updated the readme.

Thank you for raising this and for the investigation. Much appreciated.

**Comment by vaibhavantil1** [comment]
Thanks @akitikkx - Did you use our tool to generate the CSV? If yes, would love some feedback 👍 

Link to tool: https://github.com/Privado-Inc/privado

**Comment by akitikkx** [comment]
Hey, @vaibhavantil1 I actually used the Google Play Store console to generate the report. However, thank you again for looking into this!
