### ISSUE TITLE
Integrate Jetpack Compose Destinations by @raamcosta

### ISSUE THREAD

**Issue by akitikkx** [akitikkx/upnext#41]
**Describe the solution you'd like**
Integrate the Jetpack Compose Destinations library by @raamcosta https://github.com/raamcosta/compose-destinations

**Documentation**
https://composedestinations.rafaelcosta.xyz

**Comment by raamcosta** [comment]
Let me know if you find anything I can help with! 🙂

**Comment by akitikkx** [comment]
Thanks so much, man 🙏
